export const CHARACTER_CREATE = 'CHARACTER_CREATE';
export const CHARACTER_DELETE = 'CHARACTER_DELETE';
export const CHARACTER_UPDATE = 'CHARACTER_UPDATE';
export const CHARACTER_UPDATE_SOME = 'CHARACTERS_UPDATE_SOME';
